id: /subscriptions/1a837392-8a07-4332-95a3-6c030fb329a2/resourceGroups/FriskyGhost-Production/providers/Microsoft.App/containerapps/clipflow-bot
identity:
  type: None
location: West US 2
name: clipflow-bot
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress: null
    maxInactiveRevisions: 100
    registries: null
    revisionTransitionThreshold: null
    runtime: null
    secrets:
    - name: telegram-token-secret
    - name: mongo-uri-secret
    - name: database-url-secret
    service: null
    targetLabel: null
  customDomainVerificationId: 12205E833111B7569571C70F9D9889B92DF2474BF7A367DEAEAD9C4611956405
  delegatedIdentities: []
  deploymentErrors: 'The following field(s) are either invalid or missing. Field ''template.containers.bot-container.image''
    is invalid with details: ''Invalid value: "ca8360d6c250acr.azurecr.io/clipflow-bot:latest":
    GET https:?scope=repository%3Aclipflow-bot%3Apull&service=ca8360d6c250acr.azurecr.io:
    UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization
    for more information. CorrelationId: f4542a5a-c0d1-49c3-836f-c1f28811bd0f'';.'
  environmentId: /subscriptions/1a837392-8a07-4332-95a3-6c030fb329a2/resourceGroups/FriskyGhost-Production/providers/Microsoft.App/managedEnvironments/friskyghost-serverless-env
  managedEnvironmentId: /subscriptions/1a837392-8a07-4332-95a3-6c030fb329a2/resourceGroups/FriskyGhost-Production/providers/Microsoft.App/managedEnvironments/friskyghost-serverless-env
  outboundIpAddresses:
  - 51.143.107.207
  patchingMode: Automatic
  provisioningState: Failed
  template:
    containers:
    - env:
      - name: TELEGRAM_BOT_TOKEN
        secretRef: telegram-token-secret
        value: ''
      - name: MONGO_URI
        secretRef: mongo-uri-secret
        value: ''
      - name: DATABASE_URL
        secretRef: database-url-secret
        value: ''
      image: ca8360d6c250acr.azurecr.io/clipflow-bot:latest
      imageType: CloudBuild
      name: bot-container
      resources:
        cpu: 1
        ephemeralStorage: 4Gi
        memory: 2.0Gi
    customMetricsSettings: null
    initContainers: null
    revisionSuffix: null
    scale:
      cooldownPeriod: null
      maxReplicas: 1
      minReplicas: 1
      pollingInterval: null
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: null
resourceGroup: FriskyGhost-Production
systemData:
  createdAt: '2026-04-10T17:00:59.6367704'
  createdBy: aroo@pupfrisky.com
  createdByType: User
  lastModifiedAt: '2026-04-16T01:41:15.9325323'
  lastModifiedBy: aroo@pupfrisky.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
